# Generated by Django 3.1.7 on 2021-03-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('agriculture', 'Agriculture'), ('business', 'Business'), ('culture', 'Culture'), ('education', 'Education'), ('environment', 'Environment'), ('food', 'Food'), ('health', 'Health'), ('sports', 'Sports'), ('style', 'Style'), ('technology', 'Technology'), ('travel', 'Travel')], default='agriculture', max_length=50),
        ),
    ]
